--[[
───────────────────────────────────────────────────────────────────────

	Speedlimit & Speedlimiter script - Created by bleachy

	(bleachy#1960) (Credits to Big Yoda for the street names & limits)

───────────────────────────────────────────────────────────────────────
]]

-- Ignore this line
Config = {}

-- Set to true if you would like the speedlimit of each road to be displayed on the HUD
Config.enableSpeedlimitDisplay = true

-- Set to true if you would like the automatic speedlimiter to be enabled
Config.enableAutomaticSpeedlimiter = true

-- You can choose from these keys https://docs.fivem.net/docs/game-references/controls/
Config.autoSpeedlimitKey = "]"

-- This will disable the speedlimit & speedlimiter from working on the below vehicle classes
-- Use https://i.imgur.com/7Jy5izx.png if you would like to disable more vehicle classes
Config.disabledVehicleClasses = {
	14, -- Boats
	15, -- Helicopters
	16, -- Planes
	21 -- Trains
}

-- This will disable the speedlimit & speedlimiter from working on the below vehicles
-- WARNING: You may need to put the vehicle model name in FULL CAPS
Config.disabledVehicles = {
	"RHINO"
}

-- Alerts that pop up when auto speed limiting is enabled/disabled
Config.enabledAlert = "Cruise control ON"
Config.disabledAlert = "Cruise control OFF"

Config.HUDPosition = {
    ["x"] = 0.0240,
    ["y"] = 0.72
} 

Config.SpeedLimits = {
    ["East Joshua Road"] = "50", 
    ["Marina Dr"] = "50", 
    ["Alhambra Dr"] = "50", 
    ["Niland Ave"] = "50", 
    ["Zancudo Ave"] = "50", 
    ["Armadillo Ave"] = "50", 
    ["Algonquin Blvd"] = "50", 
    ["Mountain View Dr"] = "50", 
    ["Cholla Springs Ave"] = "50", 
    ["Panorama Dr"] = "50", 
    ["Lesbos Ln"] = "50", 
    ["Calafia Rd"] = "50", 
    ["North Calafia Way"] = "50", 
    ["Cassidy Trail"] = "50", 
    ["Seaview Rd"] = "50", 
    ["Grapeseed Main St"] = "50", 
    ["Grapeseed Ave"] = "50", 
    ["Joad Ln"] = "50", 
    ["Union Rd"] = "50", 
    ["O'Neil Way"] = "50", 
    ["Senora Fwy"] = "100", 
    ["Catfish View"] = "50", 
    ["Great Ocean Hwy"] = "80", 
    ["Paleto Blvd"] = "50", 
    ["Duluoz Ave"] = "50", 
    ["Procopio Dr"] = "50", 
    ["Cascabel Ave"] = "50", 
    ["Procopio Promenade"] = "50", 
    ["Pyrite Ave"] = "50", 
    ["Fort Zancudo Approach Rd"] = "50", 
    ["Barbareno Rd"] = "50", 
    ["Ineseno Road"] = "50", 
    ["West Eclipse Blvd"] = "50", 
    ["Playa Vista"] = "50", 
    ["Bay City Ave"] = "50", 
    ["Del Perro Fwy"] = "80", 
    ["Equality Way"] = "50", 
    ["Red Desert Ave"] = "50", 
    ["Magellan Ave"] = "50", 
    ["Sandcastle Way"] = "50", 
    ["Vespucci Blvd"] = "50", 
    ["Prosperity St"] = "50", 
    ["San Andreas Ave"] = "50", 
    ["North Rockford Dr"] = "50", 
    ["South Rockford Dr"] = "50", 
    ["Marathon Ave"] = "50", 
    ["Boulevard Del Perro"] = "50", 
    ["Cougar Ave"] = "50", 
    ["Liberty St"] = "50", 
    ["Bay City Incline"] = "50", 
    ["Conquistador St"] = "50", 
    ["Cortes St"] = "50", 
    ["Vitus St"] = "50", 
    ["Aguja St"] = "50", 
    ["Goma St"] = "50", 
    ["Melanoma St"] = "50", 
    ["Palomino Ave"] = "50", 
    ["Invention Ct"] = "50", 
    ["Imagination Ct"] = "50", 
    ["Rub St"] = "50", 
    ["Tug St"] = "50", 
    ["Ginger St"] = "50", 
    ["Lindsay Circus"] = "50", 
    ["Calais Ave"] = "50", 
    ["Adam's Apple Blvd"] = "50", 
    ["Alta St"] = "50", 
    ["Integrity Way"] = "50", 
    ["Swiss St"] = "50", 
    ["Strawberry Ave"] = "50", 
    ["Capital Blvd"] = "50", 
    ["Crusade Rd"] = "50", 
    ["Innocence Blvd"] = "50", 
    ["Davis Ave"] = "50", 
    ["Little Bighorn Ave"] = "50", 
    ["Roy Lowenstein Blvd"] = "50", 
    ["Jamestown St"] = "50", 
    ["Carson Ave"] = "50", 
    ["Grove St"] = "50", 
    ["Brouge Ave"] = "50", 
    ["Covenant Ave"] = "50", 
    ["Dutch London St"] = "50", 
    ["Signal St"] = "50", 
    ["Elysian Fields Fwy"] = "50", 
    ["Plaice Pl"] = "50", 
    ["Chum St"] = "50", 
    ["Chupacabra St"] = "50", 
    ["Miriam Turner Overpass"] = "50", 
    ["Autopia Pkwy"] = "50", 
    ["Exceptionalists Way"] = "50", 
    ["La Puerta Fwy"] = "80", 
    ["New Empire Way"] = "50", 
    ["Runway1"] = "", 
    ["Greenwich Pkwy"] = "50", 
    ["Kortz Dr"] = "50", 
    ["Banham Canyon Dr"] = "50", 
    ["Buen Vino Rd"] = "50", 
    ["Route 68"] = "50", 
    ["Zancudo Grande Valley"] = "50", 
    ["Zancudo Barranca"] = "50", 
    ["Galileo Rd"] = "50", 
    ["Mt Vinewood Dr"] = "50", 
    ["Marlowe Dr"] = "50", 
    ["Milton Rd"] = "50", 
    ["Kimble Hill Dr"] = "50", 
    ["Normandy Dr"] = "50", 
    ["Hillcrest Ave"] = "50", 
    ["Hillcrest Ridge Access Rd"] = "50", 
    ["North Sheldon Ave"] = "50", 
    ["Lake Vinewood Dr"] = "50", 
    ["Lake Vinewood Est"] = "50", 
    ["Baytree Canyon Rd"] = "50", 
    ["North Conker Ave"] = "50", 
    ["Wild Oats Dr"] = "50", 
    ["Whispymound Dr"] = "50", 
    ["Didion Dr"] = "50", 
    ["Cox Way"] = "50", 
    ["Picture Perfect Drive"] = "50", 
    ["South Mo Milton Dr"] = "50", 
    ["Cockingend Dr"] = "50", 
    ["Mad Wayne Thunder Dr"] = "50", 
    ["Hangman Ave"] = "50", 
    ["Dunstable Ln"] = "50", 
    ["Dunstable Dr"] = "50", 
    ["Greenwich Way"] = "50", 
    ["Greenwich Pl"] = "50", 
    ["Hardy Way"] = "50", 
    ["Richman St"] = "50", 
    ["Ace Jones Dr"] = "50", 
    ["Los Santos Freeway"] = "100", 
    ["Senora Rd"] = "50", 
    ["Nowhere Rd"] = "50", 
    ["Smoke Tree Rd"] = "50", 
    ["Cholla Rd"] = "50", 
    ["Cat-Claw Ave"] = "50", 
    ["Senora Way"] = "50", 
    ["Palomino Fwy"] = "100", 
    ["Shank St"] = "50", 
    ["Macdonald St"] = "50", 
    ["Route 68 Approach"] = "50", 
    ["Vinewood Park Dr"] = "50", 
    ["Vinewood Blvd"] = "50", 
    ["Mirror Park Blvd"] = "50", 
    ["Glory Way"] = "50", 
    ["Bridge St"] = "50", 
    ["West Mirror Drive"] = "50", 
    ["Nikola Ave"] = "50", 
    ["East Mirror Dr"] = "50", 
    ["Nikola Pl"] = "50", 
    ["Mirror Pl"] = "50", 
    ["El Rancho Blvd"] = "50", 
    ["Olympic Fwy"] = "100", 
    ["Fudge Ln"] = "50", 
    ["Amarillo Vista"] = "50", 
    ["Labor Pl"] = "50", 
    ["El Burro Blvd"] = "50", 
    ["Sustancia Rd"] = "50", 
    ["South Shambles St"] = "50", 
    ["Hanger Way"] = "50", 
    ["Orchardville Ave"] = "50", 
    ["Popular St"] = "50", 
    ["Buccaneer Way"] = "50", 
    ["Abattoir Ave"] = "50", 
    ["Voodoo Place"] = "50", 
    ["Mutiny Rd"] = "50", 
    ["South Arsenal St"] = "50", 
    ["Forum Dr"] = "50", 
    ["Morningwood Blvd"] = "50", 
    ["Dorset Dr"] = "50", 
    ["Caesars Place"] = "50", 
    ["Spanish Ave"] = "50", 
    ["Portola Dr"] = "50", 
    ["Edwood Way"] = "50", 
    ["San Vitus Blvd"] = "50", 
    ["Eclipse Blvd"] = "50", 
    ["Gentry Lane"] = "50", 
    ["Las Lagunas Blvd"] = "50", 
    ["Power St"] = "50", 
    ["Mt Haan Rd"] = "50", 
    ["Elgin Ave"] = "50", 
    ["Hawick Ave"] = "50", 
    ["Meteor St"] = "50", 
    ["Alta Pl"] = "50", 
    ["Occupation Ave"] = "50", 
    ["Carcer Way"] = "50", 
    ["Eastbourne Way"] = "50", 
    ["Rockford Dr"] = "50", 
    ["Abe Milton Pkwy"] = "50", 
    ["Laguna Pl"] = "50", 
    ["Sinners Passage"] = "50", 
    ["Atlee St"] = "50", 
    ["Sinner St"] = "50", 
    ["Supply St"] = "50", 
    ["Amarillo Way"] = "50", 
    ["Tower Way"] = "50", 
    ["Decker St"] = "50", 
    ["Tackle St"] = "50", 
    ["Low Power St"] = "50", 
    ["Clinton Ave"] = "50", 
    ["Fenwell Pl"] = "50", 
    ["Utopia Gardens"] = "50", 
    ["Cavalry Blvd"] = "50", 
    ["South Boulevard Del Perro"] = "50", 
    ["Americano Way"] = "50", 
    ["Sam Austin Dr"] = "50", 
    ["East Galileo Ave"] = "50", 
    ["Galileo Park"] = "50", 
    ["West Galileo Ave"] = "50", 
    ["Tongva Dr"] = "50", 
    ["Zancudo Rd"] = "50", 
    ["Movie Star Way"] = "50", 
    ["Heritage Way"] = "50", 
    ["Perth St"] = "50", 
    ["Chianski Passage"] = "50", 
    ["Lolita Ave"] = "50", 
    ["Meringue Ln"] = "50", 
    ["Joshua Rd"] = "50"
}
